name: workflow checking code
on:
 workflow_call:
  inputs:
     workingDirectory:
      required: true
      type: string
jobs:
  lintandtest: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: install nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '18.8.0'
        cache: 'yarn'
        cache-dependency-path: ${{ inputs.workingDirectory }}/package.json
    - name: Install all packages
      working-directory: ${{ inputs.workingDirectory }}
#       run: yarn install --frozen-lockfile
      run: yarn install
    - name: run lint
      working-directory: ${{ inputs.workingDirectory }}
      run: |
            yarn lint:fix
            yarn test
    

    
       


    
